server:
  port: 8111

spring:
  application:
    name: learn-cloud-gateway
  #是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。
  #默认为 false，设为 true 便开启通过服务中心的自动根据 serviceId 创建路由的功能。
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: add_request_parameter_route
        #使用负载均衡查找服务
        uri: lb://learn-cloud-producer
        filters:
        - AddRequestParameter=foo, bar
        predicates:
          - Method=GET

loggin:
  level:
    org.springframework.cloud.gateway: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/,http://localhost:8003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
